version: "3.8"

services:
  app:
    build: .
    container_name: docker-node-app
    ports:
      - "3001:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3000